-- Carrega as matrizes de Língua Portuguesa (BNCC) do 5º e do 9º ano do
-- Ensino Fundamental, seguindo o mesmo padrão da migration anterior
-- (2026-10-07-matrizes-descritores.sql, que já criou as tabelas e carregou
-- a do 2º ano).
--
-- Seguro para rodar a qualquer momento: usa upsert, não apaga nem duplica.

-- ========== Matriz de Língua Portuguesa – 5º ano (BNCC) ==========

with nova_matriz as (
  insert into public.matrizes (disciplina, serie, nome)
  values ('Língua Portuguesa', '5º ano', 'Matriz de Habilidades de Língua Portuguesa da BNCC – 5º ano do Ensino Fundamental')
  on conflict (disciplina, serie) do update set nome = excluded.nome
  returning id
)
insert into public.descritores (matriz, codigo, eixo, codigo_bncc, descricao)
select nova_matriz.id, v.codigo, v.eixo, v.codigo_bncc, v.descricao
from nova_matriz, (values
  ('D1',  'I. Leitura', 'EF15LP03', 'Localizar informações explícitas em textos. (todos os campos de atuação)'),
  ('D2',  'I. Leitura', 'EF35LP03', 'Identificar a ideia central do texto, demonstrando compreensão global. (todos os campos de atuação)'),
  ('D3',  'I. Leitura', 'EF35LP04', 'Inferir informações implícitas nos textos lidos. (todos os campos de atuação)'),
  ('D4',  'I. Leitura', 'EF35LP05', 'Inferir o sentido de palavras ou expressões desconhecidas em textos, com base no contexto da frase ou do texto. (todos os campos de atuação)'),
  ('D5',  'I. Leitura', 'EF35LP06', 'Recuperar relações entre partes de um texto, identificando substituições lexicais (de substantivos por sinônimos) ou pronominais (uso de pronomes anafóricos – pessoais, possessivos, demonstrativos) que contribuem para a continuidade do texto. (todos os campos de atuação)'),
  ('D6',  'I. Leitura', 'EF15LP14', 'Construir o sentido de histórias em quadrinhos e tirinhas, relacionando imagens e palavras e interpretando recursos gráficos (tipos de balões, de letras, onomatopeias). (campo da vida cotidiana)'),
  ('D7',  'I. Leitura', 'EF15LP18', 'Relacionar texto com ilustrações e outros recursos gráficos. (campo artístico-literário)'),
  ('D8',  'I. Leitura', 'EF05LP09', 'Ler e compreender, com autonomia, textos instrucionais de regras de jogo, dentre outros gêneros do campo da vida cotidiana, de acordo com as convenções do gênero e considerando a situação comunicativa e a finalidade do texto. (campo da vida cotidiana)'),
  ('D9',  'I. Leitura', 'EF05LP10', 'Ler e compreender, com autonomia, anedotas, piadas e cartuns, dentre outros gêneros do campo da vida cotidiana, de acordo com as convenções do gênero e considerando a situação comunicativa e a finalidade do texto. (campo da vida cotidiana)'),
  ('D10', 'I. Leitura', 'EF04LP14', 'Identificar, em notícias, fatos, participantes, local e momento/tempo da ocorrência do fato noticiado. (campo da vida pública)'),
  ('D11', 'I. Leitura', 'EF04LP15', 'Distinguir fatos de opiniões/sugestões em textos (informativos, jornalísticos, publicitários etc.). (campo da vida pública)'),
  ('D12', 'I. Leitura', 'EF04LP19', 'Ler e compreender textos expositivos de divulgação científica para crianças, considerando a situação comunicativa e o tema/assunto do texto. (campo das práticas de estudo e pesquisa)'),
  ('D13', 'I. Leitura', 'EF05LP23', 'Comparar informações apresentadas em gráficos ou tabelas.'),
  ('D14', 'I. Leitura', 'EF04LP20', 'Reconhecer a função de gráficos, diagramas e tabelas em textos, como forma de apresentação de dados e informações. (campo das práticas de estudo e pesquisa)'),
  ('D15', 'I. Leitura', 'EF03LP18', 'Ler e compreender, com autonomia, cartas dirigidas a veículos da mídia impressa ou digital (cartas de leitor e de reclamação a jornais, revistas) e notícias, dentre outros gêneros do campo jornalístico, de acordo com as convenções do gênero carta e considerando a situação comunicativa e o tema/assunto do texto. (campo da vida pública)'),
  ('D16', 'I. Leitura', 'EF35LP21', 'Ler e compreender, de forma autônoma, textos literários de diferentes gêneros e extensões, inclusive aqueles sem ilustrações, estabelecendo preferências por gêneros, temas, autores. (campo artístico-literário)'),
  ('D17', 'I. Leitura', 'EF35LP22', 'Perceber diálogos em textos narrativos, observando o efeito de sentido de verbos de enunciação e, se for o caso, o uso de variedades linguísticas no discurso direto. (campo artístico-literário)'),
  ('D18', 'II. Produção de Textos (escrita compartilhada e autônoma)', 'EF35LP26', 'Ler e compreender, com certa autonomia, narrativas ficcionais que apresentem cenários e personagens, observando os elementos da estrutura narrativa: enredo, tempo, espaço, personagens, narrador e a construção do discurso indireto e discurso direto. (campo artístico-literário)'),
  ('D19', 'II. Produção de Textos (escrita compartilhada e autônoma)', 'EF35LP27', 'Ler e compreender, com certa autonomia, textos em versos, explorando rimas, sons e jogos de palavras, imagens poéticas (sentidos figurados) e recursos visuais e sonoros. (campo artístico-literário)'),
  ('D20', 'III. Análise linguística/semiótica (Ortografização)', 'EF04LP26', 'Observar, em poemas concretos, o formato, a distribuição e a diagramação das letras do texto na página. (campo artístico-literário)'),
  ('D21', 'III. Análise linguística/semiótica (Ortografização)', 'EF05LP04', 'Diferenciar, na leitura de textos, vírgula, ponto e vírgula, dois pontos e reconhecer, na leitura de textos, o efeito de sentido que decorre do uso de reticências, aspas, parênteses. (todos os campos de atuação)'),
  ('D22', 'III. Análise linguística/semiótica (Ortografização)', 'EF05LP05', 'Identificar a expressão de presente, passado e futuro em tempos verbais do modo indicativo. (todos os campos de atuação)'),
  ('D23', 'III. Análise linguística/semiótica (Ortografização)', 'EF05LP07', 'Identificar, em textos, o uso de conjunções e a relação que estabelecem entre partes do texto: adição, oposição, tempo, causa, condição, finalidade. (todos os campos de atuação)'),
  ('D24', 'III. Análise linguística/semiótica (Ortografização)', 'EF35LP29', 'Identificar, em narrativas, cenário, personagem central, conflito gerador, resolução e o ponto de vista com base no qual histórias são narradas, diferenciando narrativas em primeira e terceira pessoas. (campo artístico-literário)'),
  ('D25', 'III. Análise linguística/semiótica (Ortografização)', 'EF35LP30', 'Diferenciar discurso indireto e discurso direto, determinando o efeito de sentido de verbos de enunciação e explicando o uso de variedades linguísticas no discurso direto, quando for o caso. (campo artístico-literário)'),
  ('D26', 'III. Análise linguística/semiótica (Ortografização)', 'EF35LP31', 'Identificar, em textos versificados, efeitos de sentido decorrentes do uso de recursos rítmicos e sonoros e de metáforas. (campo artístico-literário)')
) as v(codigo, eixo, codigo_bncc, descricao)
on conflict (matriz, codigo) do update
  set eixo = excluded.eixo, codigo_bncc = excluded.codigo_bncc, descricao = excluded.descricao;

-- ========== Matriz de Língua Portuguesa – 9º ano (BNCC) ==========

with nova_matriz as (
  insert into public.matrizes (disciplina, serie, nome)
  values ('Língua Portuguesa', '9º ano', 'Matriz de Habilidades de Língua Portuguesa da BNCC – 9º ano do Ensino Fundamental')
  on conflict (disciplina, serie) do update set nome = excluded.nome
  returning id
)
insert into public.descritores (matriz, codigo, eixo, codigo_bncc, descricao)
select nova_matriz.id, v.codigo, v.eixo, v.codigo_bncc, v.descricao
from nova_matriz, (values
  ('D1',  'I. Leitura', 'EF69LP03', 'Identificar, em notícias, o fato central, suas principais circunstâncias e eventuais decorrências; em reportagens e fotorreportagens o fato ou a temática retratada e a perspectiva de abordagem; em entrevistas os principais temas/subtemas abordados, explicações dadas ou teses defendidas em relação a esses subtemas; em tirinhas, memes, charge, a crítica, ironia ou humor presente. (campo jornalístico-midiático)'),
  ('D2',  'I. Leitura', 'EF67LP03', 'Comparar informações sobre um mesmo fato divulgadas em diferentes veículos e mídias, analisando e avaliando a confiabilidade. (campo jornalístico-midiático)'),
  ('D3',  'I. Leitura', 'EF89LP04', 'Identificar e avaliar teses/opiniões/posicionamentos explícitos e implícitos, argumentos e contra-argumentos em textos argumentativos do campo (carta de leitor, comentário, artigo de opinião, resenha crítica etc.), posicionando-se frente à questão controversa de forma sustentada. (campo jornalístico-midiático)'),
  ('D4',  'I. Leitura', 'EF89LP32', 'Analisar os efeitos de sentido decorrentes do uso de mecanismos de intertextualidade (referências, alusões, retomadas) entre os textos literários, entre esses textos literários e outras manifestações artísticas (cinema, teatro, artes visuais e midiáticas, música), quanto aos temas, personagens, estilos, autores etc., e entre o texto original e paródias, paráfrases, pastiches, trailer honesto, vídeos-minuto, vidding, dentre outros. (campo artístico-literário)'),
  ('D5',  'I. Leitura', 'EF69LP04', 'Identificar e analisar os efeitos de sentido que fortalecem a persuasão nos textos publicitários, relacionando as estratégias de persuasão e apelo ao consumo com os recursos linguístico-discursivos utilizados, como imagens, tempo verbal, jogos de palavras, figuras de linguagem etc., com vistas a fomentar práticas de consumo conscientes. (campo jornalístico-midiático)'),
  ('D6',  'I. Leitura', 'EF08LP01', 'Identificar e comparar as várias editorias de jornais impressos e digitais e de sites noticiosos, de forma a refletir sobre os tipos de fato que são noticiados e comentados, as escolhas sobre o que noticiar e o que não noticiar e o destaque/enfoque dado e a fidedignidade da informação. (campo jornalístico-midiático)'),
  ('D7',  'I. Leitura', 'EF09LP01', 'Analisar o fenômeno da disseminação de notícias falsas nas redes sociais e desenvolver estratégias para reconhecê-las, a partir da verificação/avaliação do veículo, fonte, data e local da publicação, autoria, URL, da análise da formatação, da comparação de diferentes fontes, da consulta a sites de curadoria que atestam a fidedignidade do relato dos fatos e denunciam boatos etc. (campo jornalístico-midiático)'),
  ('D8',  'I. Leitura', 'EF89LP02', 'Analisar diferentes práticas (curtir, compartilhar, comentar, curar etc.) e textos pertencentes a diferentes gêneros da cultura digital (meme, gif, comentário, charge digital etc.) envolvidos no trato com a informação e opinião, de forma a possibilitar uma presença mais crítica e ética nas redes. (campo jornalístico-midiático)'),
  ('D9',  'I. Leitura', 'EF69LP47', 'Analisar, em textos narrativos ficcionais, as diferentes formas de composição próprias de cada gênero, os recursos coesivos que constroem a passagem do tempo e articulam suas partes, a escolha lexical típica de cada gênero para a caracterização dos cenários e dos personagens e os efeitos de sentido decorrentes dos tempos verbais, dos tipos de discurso, dos verbos de enunciação e das variedades linguísticas (no discurso direto, se houver) empregados, identificando o enredo e o foco narrativo e percebendo como se estrutura a narrativa nos diferentes gêneros e os efeitos de sentido decorrentes do foco narrativo típico de cada gênero, da caracterização dos espaços físico e psicológico e dos tempos cronológico e psicológico, das diferentes vozes no texto (do narrador, de personagens em discurso direto e indireto), do uso de pontuação expressiva, palavras e expressões conotativas e processos figurativos e do uso de recursos linguístico-gramaticais próprios a cada gênero narrativo. (campo artístico-literário)'),
  ('D10', 'I. Leitura', 'EF69LP48', 'Interpretar, em poemas, efeitos produzidos pelo uso de recursos expressivos sonoros (estrofação, rimas, aliterações etc.), semânticos (figuras de linguagem, por exemplo), gráfico-espacial (distribuição da mancha gráfica no papel), imagens e sua relação com o texto verbal. (campo artístico-literário)'),
  ('D11', 'I. Leitura', 'EF67LP06', 'Identificar os efeitos de sentido provocados pela seleção lexical, topicalização de elementos e seleção e hierarquização de informações, uso de 3ª pessoa etc. (campo jornalístico-midiático)'),
  ('D12', 'II. Análise linguística/semiótica', 'EF89LP14', 'Analisar, em textos argumentativos e propositivos, os movimentos argumentativos de sustentação, refutação e negociação e os tipos de argumentos, avaliando a força/tipo dos argumentos utilizados. (campo jornalístico-midiático)'),
  ('D13', 'II. Análise linguística/semiótica', 'EF89LP16', 'Analisar a modalização realizada em textos noticiosos e argumentativos, por meio das modalidades apreciativas, viabilizadas por classes e estruturas gramaticais como adjetivos, locuções adjetivas, advérbios, locuções adverbiais, orações adjetivas e adverbiais, orações relativas restritivas e explicativas etc., de maneira a perceber a apreciação ideológica sobre os fatos noticiados ou as posições implícitas ou assumidas. (campo jornalístico-midiático)'),
  ('D14', 'II. Análise linguística/semiótica', 'EF08LP15', 'Estabelecer relações entre partes do texto, identificando o antecedente de um pronome relativo ou o referente comum de uma cadeia de substituições lexicais. (todos os campos de atuação)'),
  ('D15', 'II. Análise linguística/semiótica', 'EF09LP08', 'Identificar, em textos lidos e em produções próprias, a relação que conjunções (e locuções conjuntivas) coordenativas e subordinativas estabelecem entre as orações que conectam. (todos os campos de atuação)'),
  ('D16', 'II. Análise linguística/semiótica', 'EF08LP09', 'Interpretar efeitos de sentido de modificadores (adjuntos adnominais – artigos definido ou indefinido, adjetivos, expressões adjetivas) em substantivos com função de sujeito ou de complemento verbal, usando-os para enriquecer seus próprios textos. (todos os campos de atuação)'),
  ('D17', 'II. Análise linguística/semiótica', 'EF09LP12', 'Identificar estrangeirismos, caracterizando-os segundo a conservação, ou não, de sua forma gráfica de origem, avaliando a pertinência, ou não, de seu uso. (todos os campos de atuação)'),
  ('D18', 'II. Análise linguística/semiótica', 'EF07LP13', 'Estabelecer relações entre partes do texto, identificando substituições lexicais (de substantivos por sinônimos) ou pronominais (uso de pronomes anafóricos pessoais, possessivos, demonstrativos), que contribuem para a continuidade do texto. (todos os campos de atuação)'),
  ('D19', 'II. Análise linguística/semiótica', 'EF89LP37', 'Analisar os efeitos de sentido do uso de figuras de linguagem como ironia, eufemismo, antítese, aliteração, assonância, dentre outras. (todos os campos de atuação)'),
  ('D20', 'II. Análise linguística/semiótica', 'EF69LP05', 'Inferir e justificar, em textos multissemióticos – tirinhas, charges, memes, gifs etc. –, o efeito de humor, ironia e/ou crítica pelo uso ambíguo de palavras, expressões ou imagens ambíguas, de clichês, de recursos iconográficos, de pontuação etc. (campo jornalístico-midiático)'),
  ('D21', 'II. Análise linguística/semiótica', 'EF69LP55', 'Reconhecer as variedades da língua falada, o conceito de norma-padrão e o de preconceito linguístico. (todos os campos de atuação)'),
  ('D22', 'II. Análise linguística/semiótica', 'EF89LP23', 'Analisar, em textos argumentativos, reivindicatórios e propositivos, os movimentos argumentativos utilizados (sustentação, refutação e negociação), avaliando a força dos argumentos utilizados. (campo de atuação na vida pública)'),
  ('D23', 'II. Análise linguística/semiótica', 'EF69LP17', 'Perceber e analisar os recursos estilísticos e semióticos dos gêneros jornalísticos e publicitários, os aspectos relativos ao tratamento da informação em notícias, como a ordenação dos eventos, as escolhas lexicais, o efeito de imparcialidade do relato, a morfologia do verbo, em textos noticiosos e argumentativos, reconhecendo marcas de pessoa, número, tempo, modo, a distribuição dos verbos nos gêneros textuais (por exemplo, as formas de pretérito em relatos; as formas de presente e futuro em gêneros argumentativos; as formas de imperativo em gêneros publicitários), o uso de recursos persuasivos em textos argumentativos diversos (como a elaboração do título, escolhas lexicais, construções metafóricas, a explicitação ou a ocultação de fontes de informação) e as estratégias de persuasão e apelo ao consumo com os recursos linguístico-discursivos utilizados (tempo verbal, jogos de palavras, metáforas, imagens). (campo jornalístico-midiático)'),
  ('D24', 'II. Análise linguística/semiótica', 'EF69LP42', 'Analisar a construção composicional dos textos pertencentes a gêneros relacionados à divulgação de conhecimentos: título, (olho), introdução, divisão do texto em subtítulos, imagens ilustrativas de conceitos, relações, ou resultados complexos (fotos, ilustrações, esquemas, gráficos, infográficos, diagramas, figuras, tabelas, mapas) etc., exposição, contendo definições, descrições, comparações, enumerações, exemplificações e remissões a conceitos e relações por meio de notas de rodapé, boxes ou links; ou título, contextualização do campo, ordenação temporal ou temática por tema ou subtema, intercalação de trechos verbais com fotos, ilustrações, áudios, vídeos etc. e reconhecer traços da linguagem dos textos de divulgação científica, fazendo uso consciente das estratégias de impessoalização da linguagem (ou de pessoalização, se o tipo de publicação e objetivos assim o demandarem, como em alguns podcasts e vídeos de divulgação científica), 3ª pessoa, presente atemporal, recurso à citação, uso de vocabulário técnico/especializado etc., como forma de ampliar suas capacidades de compreensão e produção de textos nesses gêneros. (campo das práticas de estudo e pesquisa)'),
  ('D25', 'II. Análise linguística/semiótica', 'EF06LP05', 'Identificar os efeitos de sentido dos modos verbais, considerando o gênero textual e a intenção comunicativa. (todos os campos de atuação)'),
  ('D26', 'II. Análise linguística/semiótica', 'EF08LP04', 'Utilizar, ao produzir texto, conhecimentos linguísticos e gramaticais: ortografia, regências e concordâncias nominal e verbal, modos e tempos verbais, pontuação etc. (todos os campos de atuação)')
) as v(codigo, eixo, codigo_bncc, descricao)
on conflict (matriz, codigo) do update
  set eixo = excluded.eixo, codigo_bncc = excluded.codigo_bncc, descricao = excluded.descricao;
